name: raion_intern_15
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  provider: ^6.1.2
  cloud_firestore: ^5.6.5
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/google_icon.png
    - lib/assets/images/lockIcon.png
    - lib/assets/images/logo.png
    - lib/assets/images/logoIcon.png
    - lib/assets/images/mailIcon.png
    - lib/assets/images/nameIcon.png
    - lib/assets/images/onBoard1.png
    - lib/assets/images/onBoard2.png
    - lib/assets/images/onBoard3.png
    - lib/assets/images/bottomWidget.png
    - lib/assets/images/navbar_icon/book.png
    - lib/assets/images/navbar_icon/health.png
    - lib/assets/images/navbar_icon/home.png
    - lib/assets/images/navbar_icon/profile.png
    - lib/assets/images/navbar_icon/happy.png
    - lib/assets/images/navbar_icon/sad.png
    - lib/assets/images/navbar_icon/anxious.png
    - lib/assets/images/navbar_icon/flat.png
    - lib/assets/images/navbar_icon/excellent.png
    - lib/assets/images/navbar_icon/profile_active.png
    - lib/assets/images/navbar_icon/book_active.png
    - lib/assets/images/navbar_icon/home_active.png
    - lib/assets/images/navbar_icon/health_active.png
    - lib/assets/images/mood/happy.png
    - lib/assets/images/mood/sad.png
    - lib/assets/images/mood/anxious.png
    - lib/assets/images/mood/flat.png
    - lib/assets/images/mood/excellent.png
    - lib/assets/images/consultation/thumbnail.png
    - lib/assets/images/radio_icon/adiksi.png
    - lib/assets/images/radio_icon/adiksi_active.png
    - lib/assets/images/radio_icon/anak.png
    - lib/assets/images/radio_icon/anak_active.png
    - lib/assets/images/radio_icon/anxiety.png
    - lib/assets/images/radio_icon/anxiety_active.png
    - lib/assets/images/radio_icon/bipolar.png
    - lib/assets/images/radio_icon/bipolar_active.png
    - lib/assets/images/radio_icon/depresi.png
    - lib/assets/images/radio_icon/depresi_active.png
    - lib/assets/images/radio_icon/hubungan.png
    - lib/assets/images/radio_icon/hubungan_active.png
    - lib/assets/images/radio_icon/lgbt.png
    - lib/assets/images/radio_icon/lgbt_active.png
    - lib/assets/images/radio_icon/makan.png
    - lib/assets/images/radio_icon/makan_active.png
    - lib/assets/images/radio_icon/skizo.png
    - lib/assets/images/radio_icon/skizo_active.png
    - lib/assets/images/radio_icon/tidur.png
    - lib/assets/images/radio_icon/tidur_active.png
