name: raion_intern_15
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  provider: ^6.1.2
  cloud_firestore: ^5.6.5
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/google_icon.png
    - lib/assets/images/lockIcon.png
    - lib/assets/images/logo.png
    - lib/assets/images/mailIcon.png
    - lib/assets/images/nameIcon.png
    - lib/assets/images/onBoard1/Anxiety 1.png
    - lib/assets/images/onBoard1/Frame-1.png
    - lib/assets/images/onBoard1/Frame.png
    - lib/assets/images/onBoard1/Frame-2.png
    - lib/assets/images/onBoard1/vector.png
    - lib/assets/images/onBoard2/vector.png
    - lib/assets/images/onBoard2/Therapy Session 1.png
    - lib/assets/images/onBoard2/vector-1.png
    - lib/assets/images/onBoard2/vector-2.png
    - lib/assets/images/onBoard3/Deep Breathing 1.png
    - lib/assets/images/onBoard3/Vector.png
    - lib/assets/images/onBoard3/Vector-1.png
    - lib/assets/images/onBoard3/Vector-2.png
    - lib/assets/images/onBoard3/Vector-3.png
    - lib/assets/images/onBoard3/Vector-4.png
