// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYykDxjGHc3xFHNFc94TtqemfrRoJP5g',
    appId: '1:205023117718:web:120bf93ebfe2eb8afdddb7',
    messagingSenderId: '205023117718',
    projectId: 'raion-intern-15',
    authDomain: 'raion-intern-15.firebaseapp.com',
    storageBucket: 'raion-intern-15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDP2K6b4YnN8fzT5-I2vrKQfYbmve7VQ',
    appId: '1:205023117718:android:dd9a9e72a92ca1d7fdddb7',
    messagingSenderId: '205023117718',
    projectId: 'raion-intern-15',
    storageBucket: 'raion-intern-15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qffc5ZjtwMlId0dZ5n434MltmODYttQ',
    appId: '1:205023117718:ios:7412195c51473d1afdddb7',
    messagingSenderId: '205023117718',
    projectId: 'raion-intern-15',
    storageBucket: 'raion-intern-15.firebasestorage.app',
    iosBundleId: 'com.example.raionIntern15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qffc5ZjtwMlId0dZ5n434MltmODYttQ',
    appId: '1:205023117718:ios:7412195c51473d1afdddb7',
    messagingSenderId: '205023117718',
    projectId: 'raion-intern-15',
    storageBucket: 'raion-intern-15.firebasestorage.app',
    iosBundleId: 'com.example.raionIntern15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYykDxjGHc3xFHNFc94TtqemfrRoJP5g',
    appId: '1:205023117718:web:6ab7fba3c90c1965fdddb7',
    messagingSenderId: '205023117718',
    projectId: 'raion-intern-15',
    authDomain: 'raion-intern-15.firebaseapp.com',
    storageBucket: 'raion-intern-15.firebasestorage.app',
  );
}
